#!/bin/bash

export ERL_LIBS=../../:../deps

erl +W w \
    -boot start_sasl \
    -name 'example@127.0.0.1' \
    -config example.config \
    -rbx inets_port 8000 \
    -eval "application:start(rbx)" \
    -eval "application:start(example)"
